### ISSUE TITLE
Ability to support istio beyond mixer ( > istio 1.7)

### ISSUE THREAD

**Issue by verysonglaa** [microsoft/Application-Insights-Istio-Adapter#13]
https://istio.io/docs/tasks/observability/mixer/metrics/collecting-metrics/

"Mixer is deprecated. The functionality provided by Mixer is being moved into the Envoy proxies. Use of Mixer with Istio will only be supported through the 1.7 release of Istio."

New default installations of istio with i.e. 1.5.1 do not work because mixer is not enabled anymore. Adapter should reflect the new architecture.

**Comment by verysonglaa** [comment]
https://istio.io/blog/2020/wasm-announce/
Is there any plan to migrate this adapter to WASM?

**Comment by piotrgwiazda** [comment]
Is there any plan for this?

**Comment by its-kevin-sullivan** [comment]
+1 to this.  Would love to know if this is something we can potentially use in the future.

**Comment by MarekLani** [comment]
1+ year later, are there any plans to provide support without using mixer?

**Comment by tokaplan** [comment]
@MarekLani unfortunately, this solution is no longer under development. I know Azure AKS team has been working on expanding their monitoring story natively (with no reliance on any service mesh), so if your workloads are in Azure, please explore what they have to offer.

**Comment by MarekLani** [comment]
@tokaplan thank you for the response, please can this be mentioned in the readme?

**Comment by tokaplan** [comment]
Done, thank you
